### ISSUE TITLE
PR this repository upstream and close this repository

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/zk-regex#9]
Before tackling this Issue, review and merge: 
- [ ] https://github.com/noir-lang/zk-regex/pull/3
- [ ] https://github.com/noir-lang/zk-regex/pull/8

### Problem

Developing on this fork long term creates frictions and inefficiencies, where progresses on the library are made down two unnecessarily diverging paths.

### Happy Case

Close this repository sooner rather than later to minimize merge conflicts upstream, and focus on developing solely upstream.

### Project Impact

Nice-to-have

### Would you like to submit a PR for this Issue?

None

**Comment by olehmisar** [comment]
where is upstream @Savio-Sou?

**Comment by olehmisar** [comment]
#8 was based on #3, so they are not two different paths

**Comment by Savio-Sou** [comment]
> where is upstream?

https://github.com/zkemail/zk-regex

**Comment by Savio-Sou** [comment]
Individual PRs to be reopened upstream by the corresponding authors 🙏
